//GET http://localhost:3000/api/v1/products/

# GET http://localhost:3000/api/v1/products/?search=Luna 3

//GET http://localhost:3000/api/v1/products/5e5a696ae20f6ce73c64e971

# POST http://localhost:3000/api/v1/users/signup
# Content-Type: application/json

# {
#   "firstName": "Gigi",
#   "lastName": "meomeow",
#   "username": "gigixinhgai",
#   "email": "giang.nguyen@integrify.io",
#   "password": "gigixinhdep"
# }

# POST http://localhost:3000/api/v1/users/
# Content-Type: application/json

# {
#   "username": "chipheo",
#   "password": "chipchipxinhdep"
# }

# PUT http://localhost:3000/api/v1/users/5e5bd30078a302273f005772
# Content-Type: application/json

# {
#   "firstName": "Gigi",
#   "lastName": "Nguyen",
#   "email": "gigi123@gmail.com",
#   "password": "gigixinhdep"
# }

# POST http://localhost:3000/api/v1/users/forgotPassword
# Content-Type: application/json

# {
#   "email": "giang.nguyen@integrify.io"
# }

# POST   http://localhost:3000/api/v1/users/resetPassword?token=42434a2ef0f5d2c5e307dc7fb834159eb75b4375c5c80631748b4926370784a5
# Content-Type: application/json

POST http://localhost:3000/api/v1/products/admin
Content-Type: application/json

{
  "name": "DHC"
}